" turn off vi compatibility mode
set nocompatible

" add ** to searchpath, allows 'fuzzy' filesearch
set path+=**

" display current and relative line numbers
set relativenumber
set number

" command line completion
set wildmenu

set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

" disable line wrapping
set nowrap

set noswapfile

" underline current line
set cursorline

" show matching braces
set showmatch 

" enable file type detection
filetype plugin indent on

" syntax highlighting
syntax enable

" full python syntax highlighting
let python_highlight_all=1

" Colorscheme
set background=dark
colorscheme solarized

hi Normal ctermbg=none

call plug#begin()

Plug 'ctrlpvim/ctrlp.vim'
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'

call plug#end()

let g:ale_lint_on_text_changed = 'never'
let g:ale_fixers = {
\   'javascript': ['eslint']
\ }
