#!/bin/bash

if [ -z "$1" ]; then
    SOURCEPATH="$GITROOT"
else
    SOURCEPATH="$GITROOT/$1"
fi

# Start new session
tmux new-session -s Dev -d -n Git

# First window for SCM
tmux send-keys -t Dev:1.1 "cd $SOURCEPATH && clear" C-m

# Second window for Editor
tmux new-window -t Dev -n Vim 
tmux send-keys -t Dev:2.1 "cd $SOURCEPATH && clear && vim" C-m

# Third window for local terminal
tmux new-window -t Dev -n Console

# Fourth window for logbook
tmux new-window -t Dev -n Logbook
tmux send-keys -t Dev:4.1 "lb" C-m

# Fifth window for gtypist
tmux new-window -t Dev -n Typing
tmux send-keys -t Dev:5.1 "typeg" C-m

# Select active window and attach
tmux select-window -t Dev:1
tmux attach -t Dev
